language: r
r:
- oldrel
- release
- devel
warnings_are_errors: true
sudo: false
os:
- linux
- osx
cache: packages
env:
  global:
  - NOT_CRAN="true"
  - secure: rU2AhW3gXxUCMZUaDNoqIYRfXH6nDvwKXRyGhLYhbE4VtiBEzj9QYYrfHGHz38bIHxuwGnSeAssccLcMawYp1T5/JEUdIAoDCKDQkamewoagR+dRiPkVJCc1zEv9ifNU8azoXVbuCklIc4+zoy0y5tX84drZnMomVmvdlVu+q6Q=
  - secure: EnbtZv/gGahCtUMi98oA/ONHKTO9iCVpNnkeUax8P3uFH57TSX/lXjLHWeJvHp22XPnAuNGYf1yxJjrID1WYPUwG5raiYFa6TgQDyluIXqmlNbI5zh1T3S6MM+MfNYHdydC0OYPJ+m2jsYymyAi1EkC4JN62+zoglVYiYZWRako=
